import {
  AutoSuggestExample,
  Card1,
  Card2Example,
  Carousel1,
  Carousel2,
  DeleteButton,
  Dropdown1Example,
  Dropdown2Example,
  Dropdown3,
  ImageAccordionExample,
  Login1,
  Modal1,
  Modal2Example,
  Navbar1,
  Navbar2,
  Navbar3,
  Parallax1,
  PasswordStrengthExample,
  RcSlider,
  ReactDropzone,
  ScrollReveal,
  Sidebar1,
  Sidebar2,
  Sidebar3,
  Sidebar4,
  Sidebar5,
  Sidebar6,
  Sidebar7,
  Table1Example,
  Table2Example,
  TrashButton,
  Widget1Example,
  Widget2,
} from "./components";

export const routes = [
  {
    name: "DeleteButton",
    path: "/buttons/delete-button",
    element: <DeleteButton />,
  },
  {
    name: "TrashButton",
    path: "/buttons/trash-button",
    element: <TrashButton />,
  },
  {
    name: "Sidebar1",
    path: "/sidebars/sidebar-1",
    element: <Sidebar1 />,
  },
  {
    name: "PasswordStrength",
    path: "/controls/password-strength",
    element: <PasswordStrengthExample />,
  },
  {
    name: "ScrollReveal",
    path: "/gsap/scroll-reveal",
    element: <ScrollReveal />,
  },
  {
    name: "ImageAccordion",
    path: "/accordions/image-accordion",
    element: <ImageAccordionExample />,
  },
  {
    name: "Login1",
    path: "/logins/login-1",
    element: <Login1 />,
  },
  {
    name: "Sidebar2",
    path: "/sidebars/sidebar-2",
    element: <Sidebar2 />,
  },
  {
    name: "Card1",
    path: "/cards/card-1",
    element: <Card1 />,
  },
  {
    name: "Modal1",
    path: "/modals/modal-1",
    element: <Modal1 />,
  },
  {
    name: "Parallax1",
    path: "/parallax/parallax-1",
    element: <Parallax1 />,
  },
  {
    name: "Dropdown1",
    path: "/dropdowns/dropdown-1",
    element: <Dropdown1Example />,
  },
  {
    name: "Widget1",
    path: "/widgets/widget-1",
    element: <Widget1Example />,
  },
  {
    name: "AutoSuggest",
    path: "/controls/auto-suggest",
    element: <AutoSuggestExample />,
  },
  {
    name: "Sidebar3",
    path: "/sidebars/sidebar-3",
    element: <Sidebar3 />,
  },
  {
    name: "Carousel1",
    path: "/carousels/carousel-1",
    element: <Carousel1 />,
  },
  {
    name: "RcSlider",
    path: "/libraries/rc-slider",
    element: <RcSlider />,
  },
  {
    name: "Modal2",
    path: "/modals/modal-2",
    element: <Modal2Example />,
  },
  {
    name: "Navbar1",
    path: "/navbars/navbar-1",
    element: <Navbar1 />,
  },
  {
    name: "Card2",
    path: "/cards/card-2",
    element: <Card2Example />,
  },
  {
    name: "Sidebar4",
    path: "/sidebars/sidebar-4",
    element: <Sidebar4 />,
  },
  {
    name: "Carousel2",
    path: "/carousels/carousel-2",
    element: <Carousel2 />,
  },
  {
    name: "Table1",
    path: "/tables/table-1",
    element: <Table1Example />,
  },
  {
    name: "Sidebar5",
    path: "/sidebars/sidebar-5",
    element: <Sidebar5 />,
  },
  {
    name: "Widget2",
    path: "/widgets/widget-2",
    element: <Widget2 />,
  },
  {
    name: "Navbar2",
    path: "/navbars/navbar-2",
    element: <Navbar2 />,
  },
  {
    name: "Dropdown2",
    path: "/dropdowns/dropdown-2",
    element: <Dropdown2Example />,
  },
  {
    name: "Sidebar6",
    path: "/sidebars/sidebar-6",
    element: <Sidebar6 />,
  },
  {
    name: "Sidebar7",
    path: "/sidebars/sidebar-7",
    element: <Sidebar7 />,
  },
  {
    name: "ReactDropzone",
    path: "/libraries/react-dropzone",
    element: <ReactDropzone />,
  },
  {
    name: "Dropdown3",
    path: "/dropdowns/dropdown-3",
    element: <Dropdown3 />,
  },
  {
    name: "Table2",
    path: "/tables/table-2",
    element: <Table2Example />,
  },
  {
    name: "Navbar3",
    path: "/navbars/navbar-3",
    element: <Navbar3 />,
  },
];
