import {
  AutoSuggestExample,
  Card1,
  Card2Example,
  Card3Example,
  Card4Example,
  Card5Example,
  Card6Example,
  Carousel1,
  Carousel2,
  Carousel3,
  DeleteButton,
  Dropdown1Example,
  Dropdown2Example,
  Dropdown3,
  Dropdown4Example,
  Dropdown5Example,
  Dropdown6Example,
  EditableTitleExample,
  FabButton,
  Accordion1Example,
  Accordion2Example,
  Accordion3Example,
  Login1,
  Login2,
  Login3,
  Modal1,
  Modal2Example,
  Navbar1,
  Navbar2,
  Navbar3,
  Parallax1,
  Parallax2,
  PasswordStrengthExample,
  PasswordStrength2Example,
  PasswordVisibilityExample,
  RcSlider,
  ReactDropzone,
  ReactXarrows,
  ScrollReveal,
  Sidebar1,
  Sidebar2,
  Sidebar3,
  Sidebar4,
  Sidebar5,
  Sidebar6,
  Sidebar7,
  Sidebar8,
  Sidebar9,
  Sidebar10,
  Sidebar11,
  Sidebar12,
  Sidebar13,
  SliderExample,
  Table1Example,
  Table2Example,
  Table3Example,
  TrashButton,
  TypedMessageExample,
  Widget1Example,
  Widget2,
} from "./components";

export const routes = [
  {
    name: "DeleteButton",
    path: "/buttons/delete-button",
    element: <DeleteButton />,
  },
  {
    name: "TrashButton",
    path: "/buttons/trash-button",
    element: <TrashButton />,
  },
  {
    name: "Sidebar1",
    path: "/sidebars/sidebar-1",
    element: <Sidebar1 />,
  },
  {
    name: "Controls - PasswordStrength",
    path: "/controls/password-strength",
    element: <PasswordStrengthExample />,
  },
  {
    name: "ScrollReveal",
    path: "/gsap/scroll-reveal",
    element: <ScrollReveal />,
  },
  {
    name: "Accordion1",
    path: "/accordions/accordion-1",
    element: <Accordion1Example />,
  },
  {
    name: "Accordion2",
    path: "/accordions/accordion-2",
    element: <Accordion2Example />,
  },
  {
    name: "Login1",
    path: "/logins/login-1",
    element: <Login1 />,
  },
  {
    name: "Sidebar2",
    path: "/sidebars/sidebar-2",
    element: <Sidebar2 />,
  },
  {
    name: "Card1",
    path: "/cards/card-1",
    element: <Card1 />,
  },
  {
    name: "Modal1",
    path: "/modals/modal-1",
    element: <Modal1 />,
  },
  {
    name: "Parallax1",
    path: "/parallax/parallax-1",
    element: <Parallax1 />,
  },
  {
    name: "Dropdown1",
    path: "/dropdowns/dropdown-1",
    element: <Dropdown1Example />,
  },
  {
    name: "Widget1",
    path: "/widgets/widget-1",
    element: <Widget1Example />,
  },
  {
    name: "Controls - AutoSuggest",
    path: "/controls/auto-suggest",
    element: <AutoSuggestExample />,
  },
  {
    name: "Sidebar3",
    path: "/sidebars/sidebar-3",
    element: <Sidebar3 />,
  },
  {
    name: "Carousel1",
    path: "/carousels/carousel-1",
    element: <Carousel1 />,
  },
  {
    name: "RcSlider",
    path: "/libraries/rc-slider",
    element: <RcSlider />,
  },
  {
    name: "Modal2",
    path: "/modals/modal-2",
    element: <Modal2Example />,
  },
  {
    name: "Navbar1",
    path: "/navbars/navbar-1",
    element: <Navbar1 />,
  },
  {
    name: "Card2",
    path: "/cards/card-2",
    element: <Card2Example />,
  },
  {
    name: "Sidebar4",
    path: "/sidebars/sidebar-4",
    element: <Sidebar4 />,
  },
  {
    name: "Carousel2",
    path: "/carousels/carousel-2",
    element: <Carousel2 />,
  },
  {
    name: "Table1",
    path: "/tables/table-1",
    element: <Table1Example />,
  },
  {
    name: "Sidebar5",
    path: "/sidebars/sidebar-5",
    element: <Sidebar5 />,
  },
  {
    name: "Widget2",
    path: "/widgets/widget-2",
    element: <Widget2 />,
  },
  {
    name: "Navbar2",
    path: "/navbars/navbar-2",
    element: <Navbar2 />,
  },
  {
    name: "Dropdown2",
    path: "/dropdowns/dropdown-2",
    element: <Dropdown2Example />,
  },
  {
    name: "Sidebar6",
    path: "/sidebars/sidebar-6",
    element: <Sidebar6 />,
  },
  {
    name: "Sidebar7",
    path: "/sidebars/sidebar-7",
    element: <Sidebar7 />,
  },
  {
    name: "ReactDropzone",
    path: "/libraries/react-dropzone",
    element: <ReactDropzone />,
  },
  {
    name: "Dropdown3",
    path: "/dropdowns/dropdown-3",
    element: <Dropdown3 />,
  },
  {
    name: "Table2",
    path: "/tables/table-2",
    element: <Table2Example />,
  },
  {
    name: "Navbar3",
    path: "/navbars/navbar-3",
    element: <Navbar3 />,
  },
  {
    name: "FabButton",
    path: "/button/fab-button",
    element: <FabButton />,
  },
  {
    name: "Controls - PasswordVisibility",
    path: "/controls/password-visibility",
    element: <PasswordVisibilityExample />,
  },
  {
    name: "Table3",
    path: "/tables/table-3",
    element: <Table3Example />,
  },
  {
    name: "Dropdown4",
    path: "/dropdowns/dropdown-4",
    element: <Dropdown4Example />,
  },
  {
    name: "Sidebar8",
    path: "/sidebars/sidebar-8",
    element: <Sidebar8 />,
  },
  {
    name: "ReactXarrows",
    path: "/libraries/react-xarrows",
    element: <ReactXarrows />,
  },
  {
    name: "GSAP - TypedMessage",
    path: "/gsap/typed-message",
    element: <TypedMessageExample />,
  },
  {
    name: "Card3",
    path: "/cards/card-3",
    element: <Card3Example />,
  },
  {
    name: "Controls - EditableText",
    path: "/controls/editable-text",
    element: <EditableTitleExample />,
  },
  {
    name: "Sidebar9",
    path: "/sidebars/sidebar-9",
    element: <Sidebar9 />,
  },
  {
    name: "Sidebar10",
    path: "/sidebars/sidebar-10",
    element: <Sidebar10 />,
  },
  {
    name: "Controls - Slider",
    path: "/controls/slider",
    element: <SliderExample />,
  },
  {
    name: "Carousel3",
    path: "/carousels/carousel-3",
    element: <Carousel3 />,
  },
  {
    name: "Card4",
    path: "/cards/card-4",
    element: <Card4Example />,
  },
  {
    name: "Parallax2",
    path: "/parallax/parallax-2",
    element: <Parallax2 />,
  },
  {
    name: "Dropdown5",
    path: "/dropdown/dropdown-5",
    element: <Dropdown5Example />,
  },
  {
    name: "Controls - PasswordStrength2",
    path: "/controls/password-strength-2",
    element: <PasswordStrength2Example />,
  },
  {
    name: "Accordion3",
    path: "/accordions/accordion-3",
    element: <Accordion3Example />,
  },
  {
    name: "Sidebar11",
    path: "/sidebars/sidebar-11",
    element: <Sidebar11 />,
  },
  {
    name: "Card5",
    path: "/cards/card-5",
    element: <Card5Example />,
  },
  {
    name: "Login2",
    path: "/logins/login-2",
    element: <Login2 />,
  },
  {
    name: "Card6",
    path: "/cards/card-6",
    element: <Card6Example />,
  },
  {
    name: "Dropdown6",
    path: "/dropdowns/dropdown-6",
    element: <Dropdown6Example />,
  },
  {
    name: "Sidebar12",
    path: "/sidebars/sidebar-12",
    element: <Sidebar12 />,
  },
  {
    name: "Login3",
    path: "/logins/login-3",
    element: <Login3 />,
  },
  {
    name: "Sidebar13",
    path: "/sidebars/sidebar-13",
    element: <Sidebar13 />,
  },
];
